kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key
              secret: "lNkJUzVQj5lYPQVQ/HTSEih+69e+2bWhROg9YTAfoYE="
      - identity: {}
